services:
  flower-final-project:
    image: postgres:alpine
    container_name: project-flower-shops
    ports:
      - "6003:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: guitars

  flower-finalproject:
    image: flower-shops
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flower-shops
    ports:
      - "6003:8083"
    environment:
      - server.port=8083
      - spring.datasource.url=jdbc:postgresql://demo-database:5432/guitars
      - spring.datasource.username=postgres
      - spring.datasource.password=password
    restart: "no"
    depends_on:
      - flower-final-project


