spring:
  datasource:
    url: jdbc:postgresql://dpg-cokkli0cmk4c739h1c50-a.ohio-postgres.render.com/ducks_wt5u
    username: ducks_wt5u_user
    password: Wn93tUSYeukaXaKQEfPKiDNmUco84PA5

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always


server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true










